/*
 * Auto-generated fuzzer wrapper
 * Generated by proto-liberator
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "pb_decode.h"
#include "input.pb.h"

/* Library Headers */

#include "test_lib.h"


/* Helper Macros */
#define MIN(a,b) (((a)<(b))?(a):(b))

int LLVMFuzzerInitialize(int *argc, char ***argv) {
    return 0;
}

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    FuzzInput message = FuzzInput_init_zero;
    pb_istream_t stream = pb_istream_from_buffer(data, size);

    if (!pb_decode(&stream, FuzzInput_fields, &message)) {
        return 0;
    }

    /* Execute API Calls */
    for (size_t i = 0; i < message.api_calls_count; i++) {
        const ApiCall *call = &message.api_calls[i];
        
        switch (call->which_call) {
            
            case ApiCall_call_test_func_tag: {
                /* test_func */
                const test_func_Params *params = &call->call.test_func;
                
                // Argument preparation
                
                int arg_param1;
                // TODO: Conversion logic for param1
                

                test_func(
                    
                    arg_param1
                    
                );
                break;
            }
            
            default:
                break;
        }
    }

    return 0;
}