/*
 * Auto-generated fuzzer wrapper (LPM / C++)
 * Generated by proto-liberator
 */

#define _GNU_SOURCE
#include <algorithm>
#include <cstdint>
#include <cstddef>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <stdarg.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <vector>
#include <climits>
#include <type_traits>

#include "src/libfuzzer/libfuzzer_macro.h"
#include "cpu_features.v2.pb.h"

/* Library Headers */
#ifdef __cplusplus
extern "C" {
#endif

#include "cpuinfo_x86.h"

#ifdef __cplusplus
}
#endif

#include "include/internal/filesystem.h"
#include "include/internal/stack_line_reader.h"
#include "include/internal/string_view.h"



// Undefine API-name macros that can collide with generated protobuf accessors
// such as `action.<field>()` in switch cases.

#ifdef fill_x86_brand_string
#undef fill_x86_brand_string
#endif
#ifdef FillX86BrandString
#undef FillX86BrandString
#endif

#ifdef get_x86_cache_info
#undef get_x86_cache_info
#endif
#ifdef GetX86CacheInfo
#undef GetX86CacheInfo
#endif

#ifdef get_x86_features_enum_name
#undef get_x86_features_enum_name
#endif
#ifdef GetX86FeaturesEnumName
#undef GetX86FeaturesEnumName
#endif

#ifdef get_x86_features_enum_value
#undef get_x86_features_enum_value
#endif
#ifdef GetX86FeaturesEnumValue
#undef GetX86FeaturesEnumValue
#endif

#ifdef get_x86_info
#undef get_x86_info
#endif
#ifdef GetX86Info
#undef GetX86Info
#endif

#ifdef get_x86_microarchitecture
#undef get_x86_microarchitecture
#endif
#ifdef GetX86Microarchitecture
#undef GetX86Microarchitecture
#endif

#ifdef get_x86_microarchitecture_name
#undef get_x86_microarchitecture_name
#endif
#ifdef GetX86MicroarchitectureName
#undef GetX86MicroarchitectureName
#endif


// Typed handle tables (prevent cross-type mixing).
static const size_t MAX_HANDLES = 1024;

enum HandleTypeId {

    HT_default = 0,

    HT__COUNT = 1
};

struct HandleTable {
    void* handles[MAX_HANDLES];
    bool valid[MAX_HANDLES];
    uint32_t count;
};

static HandleTable g_tables[HT__COUNT];

static void handles_reset() {
    for (size_t t = 0; t < (size_t)HT__COUNT; t++) {
        g_tables[t].count = 0;
        std::memset(g_tables[t].handles, 0, sizeof(g_tables[t].handles));
        std::memset(g_tables[t].valid, 0, sizeof(g_tables[t].valid));
    }
}

static uint32_t handle_register(uint32_t type_id, void *ptr) {
    if (!ptr) return 0;
    if (type_id >= (uint32_t)HT__COUNT) return 0;
    HandleTable& tab = g_tables[type_id];
    if (tab.count + 1 >= MAX_HANDLES) return 0;
    uint32_t id = ++tab.count;
    tab.handles[id] = ptr;
    tab.valid[id] = true;
    return id;
}

static uint32_t handle_select(uint32_t type_id, uint32_t requested) {
    if (type_id >= (uint32_t)HT__COUNT) return 0;
    HandleTable& tab = g_tables[type_id];
    if (tab.count == 0) return 0;
    if (requested == 0) return tab.count; /* latest */
    uint32_t idx = requested % tab.count;
    if (idx == 0) idx = tab.count;
    return idx;
}

static void *handle_get(uint32_t type_id, uint32_t requested, bool allow_stale, uint32_t *out_selected) {
    uint32_t idx = handle_select(type_id, requested);
    if (out_selected) *out_selected = idx;
    if (idx == 0) return NULL;
    if (type_id >= (uint32_t)HT__COUNT) return NULL;
    HandleTable& tab = g_tables[type_id];
    if (allow_stale || tab.valid[idx]) return tab.handles[idx];
    return NULL;
}

static void handle_invalidate(uint32_t type_id, uint32_t selected) {
    if (type_id >= (uint32_t)HT__COUNT) return;
    HandleTable& tab = g_tables[type_id];
    if (selected == 0 || selected > tab.count) return;
    tab.valid[selected] = false;
}

// -----------------------------------------------------------------------------
// API stats (per-process; orchestrator merges api_stats.*.json)
// -----------------------------------------------------------------------------

static const size_t API_COUNT = 7;
static uint64_t g_api_seen[7];
static uint64_t g_api_executed[7];
static uint64_t g_api_skipped[7];

static void ensure_dir_recursive(const char* dir) {
    if (!dir || !dir[0]) return;
    char tmp[4096];
    std::snprintf(tmp, sizeof(tmp), "%s", dir);
    size_t len = std::strlen(tmp);
    if (len == 0) return;
    if (tmp[len - 1] == '/') tmp[len - 1] = 0;
    for (char* p = tmp + 1; *p; ++p) {
        if (*p == '/') {
            *p = 0;
            mkdir(tmp, 0755);
            *p = '/';
        }
    }
    mkdir(tmp, 0755);
}

static void ensure_parent_dir(const char* path) {
    if (!path) return;
    const char* slash = std::strrchr(path, '/');
    if (!slash) return;
    size_t len = (size_t)(slash - path);
    if (len == 0 || len >= 4096) return;
    char dir[4096];
    std::memcpy(dir, path, len);
    dir[len] = 0;
    ensure_dir_recursive(dir);
}

static void api_stats_path(char* out, size_t out_sz) {
    const char* base = std::getenv("PROTO_LIBERATOR_API_STATS");
    if (!base || !base[0]) base = "api_stats/api_stats.json";
    pid_t pid = getpid();

    const char* dot = std::strrchr(base, '.');
    if (dot && std::strcmp(dot, ".json") == 0) {
        int prefix_len = (int)(dot - base);
        std::snprintf(out, out_sz, "%.*s.%d.json", prefix_len, base, (int)pid);
        return;
    }
    std::snprintf(out, out_sz, "%s.%d.json", base, (int)pid);
}

static void write_api_stats() {
    if (API_COUNT == 0) return;
    char path[4096];
    api_stats_path(path, sizeof(path));
    ensure_parent_dir(path);
    FILE* f = std::fopen(path, "w");
    if (!f) return;

    std::fprintf(f, "{\n  \"apis\": [\n");
    
    {
        size_t idx = 0;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "FillX86BrandString",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 1;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86CacheInfo",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 2;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86FeaturesEnumName",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 3;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86FeaturesEnumValue",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 4;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86Info",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 5;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86Microarchitecture",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ","
        );
    }
    
    {
        size_t idx = 6;
        std::fprintf(
            f,
            "    {\"name\":\"%s\",\"seen\":%llu,\"executed\":%llu,\"skipped\":%llu}%s\n",
            "GetX86MicroarchitectureName",
            (unsigned long long)g_api_seen[idx],
            (unsigned long long)g_api_executed[idx],
            (unsigned long long)g_api_skipped[idx],
            ""
        );
    }
    
    std::fprintf(f, "  ]\n}\n");
    std::fclose(f);
}

struct ApiStatsAutoInit {
    ApiStatsAutoInit() { std::atexit(write_api_stats); }
};
static ApiStatsAutoInit g_api_stats_autoinit;

static void* align_up(void* p, size_t align) {
    uintptr_t v = (uintptr_t)p;
    uintptr_t a = (uintptr_t)align;
    v = (v + (a - 1)) & ~(a - 1);
    return (void*)v;
}

static size_t choose_n_override(
    size_t available,
    bool has_override,
    uint32_t length_override,
    bool has_length,
    uint32_t length
) {
    size_t n = 0;
    if (has_override && length_override) {
        n = static_cast<size_t>(length_override);
    } else if (has_length && length) {
        n = static_cast<size_t>(length);
    } else {
        n = available;
    }
    return std::min(n, available);
}

static int env_int(const char* name, int def_val) {
    const char* val = std::getenv(name);
    if (!val || !val[0]) return def_val;
    char* end = nullptr;
    long parsed = std::strtol(val, &end, 10);
    if (end == val) return def_val;
    if (parsed < 0) return 0;
    if (parsed > INT_MAX) return INT_MAX;
    return static_cast<int>(parsed);
}

static bool env_allowlist_has(const char* list, const char* name) {
    if (!list || !list[0] || !name || !name[0]) return false;
    size_t name_len = std::strlen(name);
    const char* p = list;
    while (*p) {
        while (*p == ',' || *p == ' ' || *p == '\t' || *p == '\n') p++;
        if (!*p) break;
        const char* start = p;
        while (*p && *p != ',' && *p != ' ' && *p != '\t' && *p != '\n') p++;
        size_t len = (size_t)(p - start);
        if (len == name_len && std::strncmp(start, name, len) == 0) {
            return true;
        }
        if (*p == ',') p++;
    }
    return false;
}

static bool allow_for_api(const char* list, const char* api_name) {
    if (!list || !list[0]) return true;
    return env_allowlist_has(list, api_name);
}

static uint32_t mix_u32(uint32_t x) {
    x ^= x >> 16;
    x *= 0x7feb352dU;
    x ^= x >> 15;
    x *= 0x846ca68bU;
    x ^= x >> 16;
    return x;
}

static bool allow_with_budget(int* budget, int prob_num, int prob_den, uint32_t salt) {
    if (!budget || *budget <= 0) return false;
    if (prob_den <= 0 || prob_num <= 0) return false;
    uint32_t v = mix_u32(salt);
    if ((int)(v % (uint32_t)prob_den) >= prob_num) return false;
    --(*budget);
    return true;
}

static const bool kSimpleHarness = true;

static const size_t STATE_POOL_CAP = 16;

struct RuntimeState {
    cpu_features::X86Info infos[STATE_POOL_CAP];
    size_t info_count;
    cpu_features::X86Microarchitecture microarches[STATE_POOL_CAP];
    size_t microarch_count;
    char brand_strings[STATE_POOL_CAP][49];
    size_t brand_count;
};

static void runtime_state_reset(RuntimeState* st) {
    if (!st) return;
    std::memset(st, 0, sizeof(*st));
}

static void runtime_add_info(RuntimeState* st, const cpu_features::X86Info& info) {
    if (!st) return;
    size_t slot = st->info_count < STATE_POOL_CAP ? st->info_count : (st->info_count % STATE_POOL_CAP);
    st->infos[slot] = info;
    st->info_count++;
}

static void runtime_add_microarchitecture(RuntimeState* st, cpu_features::X86Microarchitecture m) {
    if (!st) return;
    size_t slot =
        st->microarch_count < STATE_POOL_CAP ? st->microarch_count : (st->microarch_count % STATE_POOL_CAP);
    st->microarches[slot] = m;
    st->microarch_count++;
}

static const cpu_features::X86Info* ensure_live_info(RuntimeState* st, uint32_t salt) {
    if (!st) return nullptr;
    if (st->info_count == 0) {
        runtime_add_info(st, cpu_features::GetX86Info());
    }
    if (st->info_count == 0) return nullptr;
    size_t count = std::min(st->info_count, STATE_POOL_CAP);
    size_t idx = (size_t)(mix_u32(salt) % (uint32_t)count);
    return &st->infos[idx];
}

static const cpu_features::X86Features* ensure_live_features(RuntimeState* st, uint32_t salt) {
    const cpu_features::X86Info* info = ensure_live_info(st, salt);
    if (!info) return nullptr;
    return &info->features;
}

static cpu_features::X86Microarchitecture ensure_live_microarchitecture(RuntimeState* st, uint32_t salt) {
    if (!st) return cpu_features::X86_UNKNOWN;
    if (st->microarch_count == 0) {
        const cpu_features::X86Info* info = ensure_live_info(st, salt ^ 0x13579BDFu);
        if (info) {
            runtime_add_microarchitecture(st, cpu_features::GetX86Microarchitecture(info));
        }
    }
    if (st->microarch_count == 0) return cpu_features::X86_UNKNOWN;
    size_t count = std::min(st->microarch_count, STATE_POOL_CAP);
    size_t idx = (size_t)(mix_u32(salt) % (uint32_t)count);
    return st->microarches[idx];
}

static char* runtime_acquire_brand_slot(RuntimeState* st) {
    if (!st) return nullptr;
    size_t slot = st->brand_count < STATE_POOL_CAP ? st->brand_count : (st->brand_count % STATE_POOL_CAP);
    st->brand_count++;
    std::memset(st->brand_strings[slot], 0, sizeof(st->brand_strings[slot]));
    return st->brand_strings[slot];
}

static cpu_features::X86FeaturesEnum clamp_feature_enum(int32_t raw, uint32_t salt) {
    const int max_enum = static_cast<int>(cpu_features::X86_LAST_);
    if (max_enum <= 0) return cpu_features::X86_FPU;
    (void)salt;
    int normalized = raw % max_enum;
    if (normalized < 0) normalized += max_enum;
    return static_cast<cpu_features::X86FeaturesEnum>(normalized);
}

static cpu_features::X86Microarchitecture clamp_microarchitecture_enum(int32_t raw, uint32_t salt) {
    const int max_enum = static_cast<int>(cpu_features::X86_MICROARCHITECTURE_LAST_);
    if (max_enum <= 0) return cpu_features::X86_UNKNOWN;
    (void)salt;
    int normalized = raw % max_enum;
    if (normalized < 0) normalized += max_enum;
    return static_cast<cpu_features::X86Microarchitecture>(normalized);
}

static void warmup_internal_string_view(uint32_t seed) {
    const char* sample = (seed & 1u)
        ? "flags: sse sse2 ssse3 avx avx2"
        : "  vendor_id  : GenuineIntel  ";
    cpu_features::StringView line = cpu_features::str(sample);
    cpu_features::StringView key = {};
    cpu_features::StringView value = {};
    (void)cpu_features::CpuFeatures_StringView_GetAttributeKeyValue(line, &key, &value);
    (void)cpu_features::CpuFeatures_StringView_IndexOfChar(line, ':');
    (void)cpu_features::CpuFeatures_StringView_IndexOf(line, cpu_features::str("sse2"));
    (void)cpu_features::CpuFeatures_StringView_IsEquals(key, cpu_features::str("flags"));
    (void)cpu_features::CpuFeatures_StringView_StartsWith(line, cpu_features::str("flags"));
    if (line.size) {
        (void)cpu_features::CpuFeatures_StringView_Front(line);
        (void)cpu_features::CpuFeatures_StringView_Back(line);
    }
    (void)cpu_features::CpuFeatures_StringView_PopFront(line, line.size + 4);
    (void)cpu_features::CpuFeatures_StringView_PopBack(line, line.size + 4);
    (void)cpu_features::CpuFeatures_StringView_KeepFront(line, line.size + 4);
    (void)cpu_features::CpuFeatures_StringView_TrimWhitespace(line);
    (void)cpu_features::CpuFeatures_StringView_ParsePositiveNumber(cpu_features::str("42"));
    (void)cpu_features::CpuFeatures_StringView_ParsePositiveNumber(cpu_features::str("0x2a"));
    (void)cpu_features::CpuFeatures_StringView_HasWord(value, "sse2", ' ');
    char out[64];
    cpu_features::CpuFeatures_StringView_CopyString(value, out, sizeof(out));
}

static void warmup_internal_file_parsing(uint32_t seed) {
    char temp_path[256];
    std::snprintf(
        temp_path,
        sizeof(temp_path),
        "/tmp/proto_liberator_cpu_features_%u_%d.tmp",
        (unsigned)seed,
        (int)getpid()
    );

    FILE* tf = std::fopen(temp_path, "wb");
    if (tf) {
        std::vector<char> long_line(4096, 'A');
        std::fwrite(long_line.data(), 1, long_line.size(), tf);
        std::fputc('\n', tf);
        std::fputs("flags: sse sse2 ssse3 avx avx2\n", tf);
        std::fputs("vendor_id: GenuineIntel\n", tf);
        std::fputs("cpu family: 6\n", tf);
        std::fclose(tf);
    }

    const char* paths[3] = {
        "/proc/cpuinfo",
        "/proc/self/status",
        temp_path,
    };

    for (size_t pi = 0; pi < 3; ++pi) {
        int fd = cpu_features::CpuFeatures_OpenFile(paths[pi]);
        if (fd < 0) continue;
        cpu_features::StackLineReader reader;
        cpu_features::StackLineReader_Initialize(&reader, fd);
        for (int i = 0; i < 64; ++i) {
            const cpu_features::LineResult lr = cpu_features::StackLineReader_NextLine(&reader);
            const cpu_features::StringView line = lr.line;
            cpu_features::StringView key = {};
            cpu_features::StringView value = {};
            (void)cpu_features::CpuFeatures_StringView_GetAttributeKeyValue(line, &key, &value);
            (void)cpu_features::CpuFeatures_StringView_HasWord(value, "sse2", ' ');
            (void)cpu_features::CpuFeatures_StringView_ParsePositiveNumber(value);
            if (line.size) {
                (void)cpu_features::CpuFeatures_StringView_Front(line);
                (void)cpu_features::CpuFeatures_StringView_Back(line);
            }
            if (lr.eof) break;
        }
        char scratch[96];
        (void)cpu_features::CpuFeatures_ReadFile(fd, scratch, sizeof(scratch));
        cpu_features::CpuFeatures_CloseFile(fd);
    }

    (void)cpu_features::CpuFeatures_OpenFile("/tmp/proto_liberator_cpu_features_missing_file");
    std::remove(temp_path);
}

static void prime_runtime_state(RuntimeState* st, uint32_t seed) {
    if (!st) return;
    // Compact stateful sequence driver: keep deep calls reachable every iteration.
    const cpu_features::X86Info info = cpu_features::GetX86Info();
    runtime_add_info(st, info);
    runtime_add_microarchitecture(st, cpu_features::GetX86Microarchitecture(&info));
    (void)cpu_features::GetX86CacheInfo();

    for (int i = 0; i < 8; ++i) {
        const auto feat = clamp_feature_enum((int32_t)(seed + (uint32_t)(17 * i)), seed ^ (uint32_t)i);
        (void)cpu_features::GetX86FeaturesEnumName(feat);
        (void)cpu_features::GetX86FeaturesEnumValue(&info.features, feat);
    }

    const auto m = ensure_live_microarchitecture(st, seed ^ 0xA5A5A5A5u);
    (void)cpu_features::GetX86MicroarchitectureName(m);

    char* brand = runtime_acquire_brand_slot(st);
    if (brand) cpu_features::FillX86BrandString(brand);
}

DEFINE_BINARY_PROTO_FUZZER(const cpu_features_fuzzer::FuzzInput& input) {
    // Reset handles
    handles_reset();
    RuntimeState runtime_state;
    runtime_state_reset(&runtime_state);
    uint32_t global_seed = input.has_global_seed() ? input.global_seed() : 0u;
    prime_runtime_state(&runtime_state, global_seed ^ 0x9E3779B9u);
    int null_budget_default = env_int("PROTO_LIBERATOR_NULL_BUDGET", kSimpleHarness ? INT_MAX : 1);
    int stale_budget_default = env_int("PROTO_LIBERATOR_STALE_BUDGET", kSimpleHarness ? INT_MAX : 0);
    int null_prob_num_default = env_int("PROTO_LIBERATOR_NULL_PROB_NUM", 1);
    int null_prob_den_default = env_int("PROTO_LIBERATOR_NULL_PROB_DEN", kSimpleHarness ? 1 : 16);
    int stale_prob_num_default = env_int("PROTO_LIBERATOR_STALE_PROB_NUM", 1);
    int stale_prob_den_default = env_int("PROTO_LIBERATOR_STALE_PROB_DEN", kSimpleHarness ? 1 : 64);
    int charpp_fallback_default = env_int("PROTO_LIBERATOR_CHARPP_FALLBACK", kSimpleHarness ? 1 : 0);
    int resize_bytes_default = env_int("PROTO_LIBERATOR_RESIZE_BYTES", kSimpleHarness ? 1 : 0);
    const char* null_allowlist = std::getenv("PROTO_LIBERATOR_NULL_ALLOWLIST");
    const char* stale_allowlist = std::getenv("PROTO_LIBERATOR_STALE_ALLOWLIST");

    int null_budget_api[API_COUNT];
    int stale_budget_api[API_COUNT];
    int null_prob_num_api[API_COUNT];
    int null_prob_den_api[API_COUNT];
    int stale_prob_num_api[API_COUNT];
    int stale_prob_den_api[API_COUNT];
    bool charpp_fallback_api[API_COUNT];
    bool resize_bytes_api[API_COUNT];
    bool allow_null_api[API_COUNT];
    bool allow_stale_api[API_COUNT];

    
    null_budget_api[0] = env_int("PROTO_LIBERATOR_NULL_BUDGET_FILL_X86_BRAND_STRING", null_budget_default);
    stale_budget_api[0] = env_int("PROTO_LIBERATOR_STALE_BUDGET_FILL_X86_BRAND_STRING", stale_budget_default);
    null_prob_num_api[0] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_FILL_X86_BRAND_STRING", null_prob_num_default);
    null_prob_den_api[0] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_FILL_X86_BRAND_STRING", null_prob_den_default);
    stale_prob_num_api[0] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_FILL_X86_BRAND_STRING", stale_prob_num_default);
    stale_prob_den_api[0] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_FILL_X86_BRAND_STRING", stale_prob_den_default);
    charpp_fallback_api[0] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_FILL_X86_BRAND_STRING", charpp_fallback_default) != 0;
    resize_bytes_api[0] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_FILL_X86_BRAND_STRING", resize_bytes_default) != 0;
    allow_null_api[0] = allow_for_api(null_allowlist, "fill_x86_brand_string");
    allow_stale_api[0] = allow_for_api(stale_allowlist, "fill_x86_brand_string");
    
    null_budget_api[1] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_CACHE_INFO", null_budget_default);
    stale_budget_api[1] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_CACHE_INFO", stale_budget_default);
    null_prob_num_api[1] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_CACHE_INFO", null_prob_num_default);
    null_prob_den_api[1] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_CACHE_INFO", null_prob_den_default);
    stale_prob_num_api[1] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_CACHE_INFO", stale_prob_num_default);
    stale_prob_den_api[1] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_CACHE_INFO", stale_prob_den_default);
    charpp_fallback_api[1] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_CACHE_INFO", charpp_fallback_default) != 0;
    resize_bytes_api[1] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_CACHE_INFO", resize_bytes_default) != 0;
    allow_null_api[1] = allow_for_api(null_allowlist, "get_x86_cache_info");
    allow_stale_api[1] = allow_for_api(stale_allowlist, "get_x86_cache_info");
    
    null_budget_api[2] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_FEATURES_ENUM_NAME", null_budget_default);
    stale_budget_api[2] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_FEATURES_ENUM_NAME", stale_budget_default);
    null_prob_num_api[2] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_FEATURES_ENUM_NAME", null_prob_num_default);
    null_prob_den_api[2] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_FEATURES_ENUM_NAME", null_prob_den_default);
    stale_prob_num_api[2] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_FEATURES_ENUM_NAME", stale_prob_num_default);
    stale_prob_den_api[2] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_FEATURES_ENUM_NAME", stale_prob_den_default);
    charpp_fallback_api[2] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_FEATURES_ENUM_NAME", charpp_fallback_default) != 0;
    resize_bytes_api[2] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_FEATURES_ENUM_NAME", resize_bytes_default) != 0;
    allow_null_api[2] = allow_for_api(null_allowlist, "get_x86_features_enum_name");
    allow_stale_api[2] = allow_for_api(stale_allowlist, "get_x86_features_enum_name");
    
    null_budget_api[3] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_FEATURES_ENUM_VALUE", null_budget_default);
    stale_budget_api[3] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_FEATURES_ENUM_VALUE", stale_budget_default);
    null_prob_num_api[3] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_FEATURES_ENUM_VALUE", null_prob_num_default);
    null_prob_den_api[3] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_FEATURES_ENUM_VALUE", null_prob_den_default);
    stale_prob_num_api[3] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_FEATURES_ENUM_VALUE", stale_prob_num_default);
    stale_prob_den_api[3] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_FEATURES_ENUM_VALUE", stale_prob_den_default);
    charpp_fallback_api[3] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_FEATURES_ENUM_VALUE", charpp_fallback_default) != 0;
    resize_bytes_api[3] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_FEATURES_ENUM_VALUE", resize_bytes_default) != 0;
    allow_null_api[3] = allow_for_api(null_allowlist, "get_x86_features_enum_value");
    allow_stale_api[3] = allow_for_api(stale_allowlist, "get_x86_features_enum_value");
    
    null_budget_api[4] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_INFO", null_budget_default);
    stale_budget_api[4] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_INFO", stale_budget_default);
    null_prob_num_api[4] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_INFO", null_prob_num_default);
    null_prob_den_api[4] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_INFO", null_prob_den_default);
    stale_prob_num_api[4] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_INFO", stale_prob_num_default);
    stale_prob_den_api[4] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_INFO", stale_prob_den_default);
    charpp_fallback_api[4] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_INFO", charpp_fallback_default) != 0;
    resize_bytes_api[4] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_INFO", resize_bytes_default) != 0;
    allow_null_api[4] = allow_for_api(null_allowlist, "get_x86_info");
    allow_stale_api[4] = allow_for_api(stale_allowlist, "get_x86_info");
    
    null_budget_api[5] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_MICROARCHITECTURE", null_budget_default);
    stale_budget_api[5] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_MICROARCHITECTURE", stale_budget_default);
    null_prob_num_api[5] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_MICROARCHITECTURE", null_prob_num_default);
    null_prob_den_api[5] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_MICROARCHITECTURE", null_prob_den_default);
    stale_prob_num_api[5] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_MICROARCHITECTURE", stale_prob_num_default);
    stale_prob_den_api[5] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_MICROARCHITECTURE", stale_prob_den_default);
    charpp_fallback_api[5] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_MICROARCHITECTURE", charpp_fallback_default) != 0;
    resize_bytes_api[5] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_MICROARCHITECTURE", resize_bytes_default) != 0;
    allow_null_api[5] = allow_for_api(null_allowlist, "get_x86_microarchitecture");
    allow_stale_api[5] = allow_for_api(stale_allowlist, "get_x86_microarchitecture");
    
    null_budget_api[6] = env_int("PROTO_LIBERATOR_NULL_BUDGET_GET_X86_MICROARCHITECTURE_NAME", null_budget_default);
    stale_budget_api[6] = env_int("PROTO_LIBERATOR_STALE_BUDGET_GET_X86_MICROARCHITECTURE_NAME", stale_budget_default);
    null_prob_num_api[6] = env_int("PROTO_LIBERATOR_NULL_PROB_NUM_GET_X86_MICROARCHITECTURE_NAME", null_prob_num_default);
    null_prob_den_api[6] = env_int("PROTO_LIBERATOR_NULL_PROB_DEN_GET_X86_MICROARCHITECTURE_NAME", null_prob_den_default);
    stale_prob_num_api[6] = env_int("PROTO_LIBERATOR_STALE_PROB_NUM_GET_X86_MICROARCHITECTURE_NAME", stale_prob_num_default);
    stale_prob_den_api[6] = env_int("PROTO_LIBERATOR_STALE_PROB_DEN_GET_X86_MICROARCHITECTURE_NAME", stale_prob_den_default);
    charpp_fallback_api[6] =
        env_int("PROTO_LIBERATOR_CHARPP_FALLBACK_GET_X86_MICROARCHITECTURE_NAME", charpp_fallback_default) != 0;
    resize_bytes_api[6] =
        env_int("PROTO_LIBERATOR_RESIZE_BYTES_GET_X86_MICROARCHITECTURE_NAME", resize_bytes_default) != 0;
    allow_null_api[6] = allow_for_api(null_allowlist, "get_x86_microarchitecture_name");
    allow_stale_api[6] = allow_for_api(stale_allowlist, "get_x86_microarchitecture_name");
    
    // Run a one-time semantic warmup so enum/string switch paths are covered
    // even when early mutations do not build stable call sequences.
    static bool warmup_done = false;
    if (!warmup_done) {
        warmup_done = true;
        warmup_internal_file_parsing(global_seed ^ 0xB5297A4Du);
        warmup_internal_string_view(global_seed ^ 0x68E31DA4u);
        char warmup_brand[128] = {0};
        cpu_features::FillX86BrandString(warmup_brand);
        const cpu_features::X86Info warmup_info = cpu_features::GetX86Info();
        const cpu_features::X86Features warmup_features = warmup_info.features;
        (void)cpu_features::GetX86CacheInfo();
        (void)cpu_features::GetX86Microarchitecture(&warmup_info);
        for (int i = -64; i <= 512; ++i) {
            const auto feat = static_cast<cpu_features::X86FeaturesEnum>(i);
            (void)cpu_features::GetX86FeaturesEnumName(feat);
            (void)cpu_features::GetX86FeaturesEnumValue(&warmup_features, feat);
        }
        for (int i = -64; i <= 256; ++i) {
            const auto m = static_cast<cpu_features::X86Microarchitecture>(i);
            (void)cpu_features::GetX86MicroarchitectureName(m);
        }
    }

    const int actions_n = std::min<int>(input.actions_size(), (int)64);
    for (int action_idx = 0; action_idx < actions_n; action_idx++) {
        const auto& action = input.actions(action_idx);
        switch (action.action_case()) {
            
            // Case for fill_x86_brand_string
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kFillX86BrandString: {
                const size_t api_idx = 0;
                g_api_seen[api_idx]++;
                
                const auto& params = action.fill_x86_brand_string();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)0;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                
                std::remove_const<char *>::type arg_0 = {};
                
                std::vector<uint8_t> storage_0;
                size_t n_0 = 0;
                bool is_null_0 = false;
                bool has_param_0 = false;
                
                
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                
                {
                    
                    if (params.has_param_0_is_null() && params.param_0_is_null()) is_null_0 = true;
                    
                    if (!is_null_0 && params.has_param_0()) {
                        has_param_0 = true;
                        const auto& bytes_0 = params.param_0();
                        size_t n = bytes_0.size();
                        
                        if (!kSimpleHarness) {
                            n = choose_n_override(
                                bytes_0.size(),
                                params.has_param_0_length_override(),
                                params.param_0_length_override(),
                                params.has_param_0_length(),
                                params.param_0_length()
                            );
                        }
                        
                        storage_0.assign(bytes_0.begin(), bytes_0.begin() + n);
                        n_0 = n;
                    }
                }
                
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                
                
                
                if (is_null_0 && !kSimpleHarness) {
                    arg_0 = (char *)nullptr;
                } else if (storage_0.empty()) {
                    arg_0 = runtime_acquire_brand_slot(&runtime_state);
                } else {
                    
                    // FillX86BrandString requires a 49-byte destination buffer.
                    if (n_0 < 48) n_0 = 48;
                    storage_0.resize(n_0 + 1);
                    storage_0[n_0] = 0;
                    
                    
                    arg_0 = (char *)(storage_0.data());
                    
                }
                
                
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                cpu_features::FillX86BrandString(
                
                    
                    arg_0
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_cache_info
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86CacheInfo: {
                const size_t api_idx = 1;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_cache_info();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)1;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86CacheInfo(
                
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_features_enum_name
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86FeaturesEnumName: {
                const size_t api_idx = 2;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_features_enum_name();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)2;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                
                std::remove_const<cpu_features::X86FeaturesEnum>::type arg_0 = {};
                
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                
                if (params.has_param_0()) {
                    arg_0 = clamp_feature_enum(params.param_0(), (uint32_t)action_idx ^ 0x2A3B4C5Du);
                } else {
                    arg_0 = clamp_feature_enum((int32_t)(global_seed + (uint32_t)action_idx), (uint32_t)action_idx);
                }
                
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                
                
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86FeaturesEnumName(
                
                    
                    arg_0
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_features_enum_value
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86FeaturesEnumValue: {
                const size_t api_idx = 3;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_features_enum_value();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)3;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                
                std::remove_const<const cpu_features::X86Features *>::type arg_0 = {};
                
                cpu_features::X86Features local_features = {};
                bool is_null_0 = false;
                bool have_local_features = false;
                
                
                std::remove_const<cpu_features::X86FeaturesEnum>::type arg_1 = {};
                
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                
                {
                    
                    if (params.has_param_0_is_null() && params.param_0_is_null()) is_null_0 = true;
                    if (kSimpleHarness) is_null_0 = false;

                    if (!is_null_0) {
                        const cpu_features::X86Features* live_features =
                            ensure_live_features(&runtime_state, (uint32_t)action_idx ^ 0x31415926u);
                        if (live_features) {
                            local_features = *live_features;
                            have_local_features = true;
                        }
                    }

                    if (!is_null_0 && have_local_features && params.has_param_0_blob()) {
                        const auto& bytes_0 = params.param_0_blob();
                        const size_t n = std::min((size_t)bytes_0.size(), sizeof(local_features));
                        if (n) std::memcpy(&local_features, bytes_0.data(), n);
                    }
                }
                
                
                
                if (params.has_param_1()) {
                    arg_1 = clamp_feature_enum(params.param_1(), (uint32_t)action_idx ^ 0x55AA00FFu);
                } else {
                    arg_1 = clamp_feature_enum((int32_t)(global_seed + (uint32_t)action_idx * 7u), (uint32_t)action_idx);
                }
                
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                
                
                if (is_null_0 || !have_local_features) {
                    arg_0 = (const cpu_features::X86Features *)nullptr;
                } else {
                    arg_0 = &local_features;
                }
                
                
                
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86FeaturesEnumValue(
                
                    
                    arg_0, 
                    
                    arg_1
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_info
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86Info: {
                const size_t api_idx = 4;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_info();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)4;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86Info(
                
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;
                runtime_add_info(&runtime_state, ret);
                runtime_add_microarchitecture(&runtime_state, cpu_features::GetX86Microarchitecture(&ret));

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_microarchitecture
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86Microarchitecture: {
                const size_t api_idx = 5;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_microarchitecture();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)5;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                
                std::remove_const<const cpu_features::X86Info *>::type arg_0 = {};
                
                cpu_features::X86Info local_info = {};
                bool is_null_0 = false;
                bool have_local_info = false;
                
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                
                {
                    
                    if (params.has_param_0_is_null() && params.param_0_is_null()) is_null_0 = true;
                    if (kSimpleHarness) is_null_0 = false;

                    if (!is_null_0) {
                        const cpu_features::X86Info* live_info =
                            ensure_live_info(&runtime_state, (uint32_t)action_idx ^ 0xDEADBEEFu);
                        if (live_info) {
                            local_info = *live_info;
                            have_local_info = true;
                        }
                    }

                    if (!is_null_0 && have_local_info && params.has_param_0_blob()) {
                        const auto& bytes_0 = params.param_0_blob();
                        const size_t n = std::min((size_t)bytes_0.size(), sizeof(local_info));
                        if (n) std::memcpy(&local_info, bytes_0.data(), n);
                    }
                }
                
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                
                
                if (is_null_0 || !have_local_info) {
                    arg_0 = (const cpu_features::X86Info *)nullptr;
                } else {
                    arg_0 = &local_info;
                }
                
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86Microarchitecture(
                
                    
                    arg_0
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;
                runtime_add_microarchitecture(&runtime_state, ret);

                // Handle destruction
                
                
                break;
            }
            
            // Case for get_x86_microarchitecture_name
            // We construct the enum value: k + CamelCase(field_name)
            // e.g. cjson_parse -> kCjsonParse
            case cpu_features_fuzzer::Action::kGetX86MicroarchitectureName: {
                const size_t api_idx = 6;
                g_api_seen[api_idx]++;
                
                const auto& params = action.get_x86_microarchitecture_name();
                int* null_budget = &null_budget_api[api_idx];
                int* stale_budget = &stale_budget_api[api_idx];
                int null_prob_num = null_prob_num_api[api_idx];
                int null_prob_den = null_prob_den_api[api_idx];
                int stale_prob_num = stale_prob_num_api[api_idx];
                int stale_prob_den = stale_prob_den_api[api_idx];
                bool charpp_fallback = charpp_fallback_api[api_idx];
                bool resize_bytes = resize_bytes_api[api_idx];
                bool allow_null = allow_null_api[api_idx];
                bool allow_stale_api_call = allow_stale_api[api_idx];

                bool should_skip_call = false;
                bool allow_stale = false;
                bool allow_double_delete = false;
                bool allow_stale_request = false;
                
                
                if (params.has_allow_double_delete() && params.allow_double_delete()) {
                    allow_double_delete = true;
                    allow_stale_request = true;
                }
                
                if (allow_stale_request && allow_stale_api_call) {
                    if (kSimpleHarness) {
                        allow_stale = true;
                    } else {
                        uint32_t salt = (uint32_t)action_idx ^ (uint32_t)6;
                        allow_stale = allow_with_budget(stale_budget, stale_prob_num, stale_prob_den, salt);
                    }
                }

                // Prepare arguments
                
                std::remove_const<cpu_features::X86Microarchitecture>::type arg_0 = {};
                
                

                // Decode/scalar-first: parse scalar and handle selectors without allocating pointer buffers.
                
                
                if (params.has_param_0()) {
                    arg_0 = clamp_microarchitecture_enum(
                        params.param_0(), (uint32_t)action_idx ^ 0x00ABCDEFu);
                } else {
                    arg_0 = ensure_live_microarchitecture(
                        &runtime_state, (uint32_t)action_idx ^ global_seed ^ 0x76543210u);
                }
                
                
                

                // Finalize pointer arguments from storage (after potential clamps/resizes).
                
                
                

                if (should_skip_call) {
                    g_api_skipped[api_idx]++;
                    break;
                }

                // Call
                
                auto ret = cpu_features::GetX86MicroarchitectureName(
                
                    
                    arg_0
                    
                );

                // Handle return
                
                g_api_executed[api_idx]++;

                // Handle destruction
                
                
                break;
            }
            
            default:
                break;
        }
    }
}
